# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Pixel
email: pixelisima@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Le site web du club Pixel de l'ISIMA, dédié aux thématiques de la création de jeux vidéos.
  Parce que ... EVERYTHING IS AWESOME !
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://Pixel-Isima.github.io" # the base hostname & protocol for your site
twitter_username:
github_username: Pixel-Isima

# Build settings
markdown: kramdown

livereload: true     # You no longer need to include --livereload